# App Engine configuration (optional alternative to Cloud Run)
runtime: nodejs18

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  NODE_ENV: production
  PORT: 3003

handlers:
  - url: /.*
    script: auto
    secure: always

