#!/bin/bash
# Script to monitor proxy server logs for trade-related activity

echo "=========================================="
echo "🔍 Trade History Debugging - Key Logs"
echo "=========================================="
echo ""
echo "1. Trade Creation (POST /api/entities/Trade):"
echo "   Look for: [PROXY] 📊 POST /api/entities/Trade"
echo "   Look for: [PROXY] 📊 ✅ Successfully saved new trade to database"
echo "   Look for: [PROXY] 🔍 saveTradeToDB CALLED"
echo "   Look for: [PROXY] 💾 ✅ Successfully saved trade to database"
echo ""
echo "2. Trade Loading from Database (on startup):"
echo "   Look for: [PROXY] 🔄 Loading trades from database into memory..."
echo "   Look for: [PROXY] ✅ Loaded X trades from database"
echo ""
echo "3. Trade Fetching (GET /api/trades - what TradeHistory uses):"
echo "   Look for: [PROXY] 📊 GET /api/trades"
echo "   Look for: [PROXY] 📊 GET /api/trades - Total trades in memory:"
echo "   Look for: [PROXY] 📊 GET /api/trades - Filtered out trades without exit_timestamp:"
echo "   Look for: [PROXY] 📊 GET /api/trades - Returning filtered trades:"
echo ""
echo "4. Errors:"
echo "   Look for: [PROXY] ❌ Error"
echo "   Look for: [PROXY] ❌ Failed to save trade"
echo ""
echo "=========================================="
echo "📋 To monitor logs in real-time, run:"
echo "   tail -f proxy.log | grep -E '(POST|GET|trades|saveTrade|Error|❌|✅)'"
echo ""
echo "Or to see all trade-related logs:"
echo "   tail -f proxy.log | grep -i trade"
echo "=========================================="

